-- Boss: Gorgash, Stormfather
-- AUTO-GENERATED by world_builder.script_generator
-- Entry: 90300
-- COMPLETE AND DEPLOYABLE - NO MANUAL CHANGES REQUIRED

local Boss = {}

-- ========================================
-- SPELL CONSTANTS
-- ========================================
local SPELL_THUNDEROUS_SLAM = 90020  -- Custom spell
local SPELL_CALL_ZEALOTS = 90021  -- Custom spell
local SPELL_PRIMAL_ROAR = 90022  -- Custom spell
local SPELL_STATIC_FIELD = 90023  -- Custom spell
local SPELL_LIGHTNING_CHARGE = 90025  -- Custom spell
local SPELL_STATIC_FIELD_DOUBLE = 90024  -- Custom spell

-- ========================================
-- PHASE CONSTANTS
-- ========================================
local PHASE_THUNDER = 1
local PHASE_LIGHTNING = 2
local PHASE_FURY = 3

-- ========================================
-- NPC CONSTANTS
-- ========================================
local NPC_STORM_ZEALOT = 90301  -- Storm Zealot

-- ========================================
-- ACHIEVEMENT TRACKING
-- ========================================
local achievement_zealot_survived_long = 0


-- ========================================
-- COMBAT EVENTS
-- ========================================
function Boss.OnEnterCombat(event, creature, target)
    -- Reset achievement tracking
    achievement_zealot_survived_long = 0


    -- Set initial phase
    creature:SetData("PHASE", 1)

    -- Phase 1 yell
    creature:SendUnitYell("The storm obeys my command! Kneel before the Stormfather!", 0)
    creature:PlayDirectSound(15020)

    -- Start Phase 1 ability timers
    creature:RegisterEvent(Boss.CastThunderousSlam, 7000, 0)
    creature:RegisterEvent(Boss.CallZealots, 12000, 0)
    creature:RegisterEvent(Boss.CastPrimalRoar, 20000, 0)

    -- Start phase check timer (every 1 second)
    creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
end

function Boss.OnLeaveCombat(event, creature)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Reset phase
    creature:SetData("PHASE", 0)

    -- Reset achievement tracking
    achievement_zealot_survived_long = 0


    -- Despawn any summoned adds
    local cleanup_1 = creature:GetCreaturesInRange(100, 90301)
    for _, add in pairs(cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

function Boss.OnDied(event, creature, killer)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Death yell
    creature:SendUnitYell("The storm... fades...", 0)
    creature:PlayDirectSound(15023)

    -- Check achievements
    -- Zealot Zapper: Defeat Gorgash without letting any Storm Zealot live longer than 10 seconds
    if achievement_zealot_survived_long == 0 then
        local players = creature:GetPlayersInRange(1000)
        for _, player in pairs(players) do
            if player:IsInCombat() then
                player:CompletedAchievement(90003)
            end
        end
    end


    -- Notify instance script
    local instance = creature:GetInstanceData()
    if instance then
        -- Update encounter state (Boss 2 = Gorgash, Stormfather)
        local encounter_id = 2
        local state = instance:GetData("ENCOUNTER_STATE") or 0
        state = bit.bor(state, bit.lshift(1, encounter_id))
        instance:SetData("ENCOUNTER_STATE", state)

        -- Unlock door
        local door = instance:GetGameObject(195002)
        if door then
            door:SetGoState(1)  -- Open
        end

        -- Save instance data
        instance:SaveInstanceData()
    end

    -- Despawn remaining adds
    local death_cleanup_1 = creature:GetCreaturesInRange(100, 90301)
    for _, add in pairs(death_cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

-- ========================================
-- PHASE TRANSITIONS
-- ========================================
function Boss.CheckPhaseTransition(event, delay, repeats, creature)
    local hp_pct = creature:GetHealthPct()
    local current_phase = creature:GetData("PHASE")

    -- Phase 2 transition at 60% HP
    if hp_pct <= 60 and current_phase == 1 then
        creature:SetData("PHASE", 2)

        -- Phase transition yell
        creature:SendUnitYell("The sky splits! Lightning answers my call!", 0)
        creature:PlayDirectSound(15021)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Start Phase 2 ability timers
        creature:RegisterEvent(Boss.CastStaticField, 5000, 0)
        creature:RegisterEvent(Boss.CastLightningCharge, 8000, 0)
        creature:RegisterEvent(Boss.CallZealotsP2, 15000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

    -- Phase 3 transition at 30% HP
    if hp_pct <= 30 and current_phase == 2 then
        creature:SetData("PHASE", 3)

        -- Phase transition yell
        creature:SendUnitYell("ENOUGH! The full fury of the storm is MINE!", 0)
        creature:PlayDirectSound(15022)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Apply buff
        creature:CastSpell(creature, 90026, false)

        -- Start Phase 3 ability timers
        creature:RegisterEvent(Boss.CastStaticFieldDouble, 3000, 0)
        creature:RegisterEvent(Boss.CastThunderousSlamP3, 5000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

end

-- ========================================
-- ABILITY FUNCTIONS
-- ========================================

-- ----------------------------------------
-- Phase 1 - Thunder
-- ----------------------------------------

-- Thunderous Slam (Frontal cone slam, heavy damage)
function Boss.CastThunderousSlam(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target current victim (tank)
    local target = creature:GetVictim()

    if target then
        creature:CastSpell(target, 90020, false)
    end

    -- Reschedule
    local next_cast = math.random(10000, 14000)
    creature:RegisterEvent(Boss.CastThunderousSlam, next_cast, 0)
end

-- Call Storm Zealots (Summons 2 Storm Zealots)
function Boss.CallZealots(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Summon 2 adds at random positions around boss
    for i = 1, 2 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 12.0 * math.cos(angle)
        local spawn_y = y + 12.0 * math.sin(angle)

        local add = creature:SummonCreature(90301, spawn_x, spawn_y, z, o, 1, 0)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.CallZealots, 25000, 0)
end

-- Primal Roar (AoE fear for 3 seconds)
function Boss.CastPrimalRoar(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90022, false)
    end

    -- Reschedule
    local next_cast = math.random(25000, 30000)
    creature:RegisterEvent(Boss.CastPrimalRoar, next_cast, 0)
end

-- ----------------------------------------
-- Phase 2 - Lightning
-- ----------------------------------------

-- Static Field (Periodic AoE damage around boss)
function Boss.CastStaticField(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90023, false)
    end

    -- Reschedule
    local next_cast = math.random(10000, 15000)
    creature:RegisterEvent(Boss.CastStaticField, next_cast, 0)
end

-- Lightning Charge (Dash to random player, damages all in path)
function Boss.CastLightningCharge(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90025, false)
    end

    -- Reschedule
    local next_cast = math.random(15000, 20000)
    creature:RegisterEvent(Boss.CastLightningCharge, next_cast, 0)
end

-- Call Storm Zealots (Continues from Phase 1)
function Boss.CallZealotsP2(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Summon 2 adds at random positions around boss
    for i = 1, 2 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 12.0 * math.cos(angle)
        local spawn_y = y + 12.0 * math.sin(angle)

        local add = creature:SummonCreature(90301, spawn_x, spawn_y, z, o, 1, 0)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.CallZealotsP2, 25000, 0)
end

-- ----------------------------------------
-- Phase 3 - Fury
-- ----------------------------------------

-- Static Field Enhanced (Double damage periodic AoE)
function Boss.CastStaticFieldDouble(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 3
    if current_phase ~= 3 then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90024, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 10000)
    creature:RegisterEvent(Boss.CastStaticFieldDouble, next_cast, 0)
end

-- Thunderous Slam (Continues, faster in P3)
function Boss.CastThunderousSlamP3(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 3
    if current_phase ~= 3 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target current victim (tank)
    local target = creature:GetVictim()

    if target then
        creature:CastSpell(target, 90020, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 10000)
    creature:RegisterEvent(Boss.CastThunderousSlamP3, next_cast, 0)
end

-- ========================================
-- HELPER FUNCTIONS
-- ========================================
function Boss.GetRandomPlayer(creature)
    local threat_list = creature:GetAITargets()
    local players = {}

    -- Filter for players only
    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            table.insert(players, unit)
        end
    end

    -- Return random player
    if #players > 0 then
        return players[math.random(1, #players)]
    end

    -- Fallback to current victim
    return creature:GetVictim()
end

function Boss.GetPlayersInMeleeRange(creature)
    local threat_list = creature:GetAITargets()
    local melee_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() and creature:GetDistance(unit) <= 5.0 then
            table.insert(melee_players, unit)
        end
    end

    return melee_players
end

function Boss.GetPlayersAtRange(creature, min_range, max_range)
    local threat_list = creature:GetAITargets()
    local ranged_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            local dist = creature:GetDistance(unit)
            if dist >= min_range and dist <= max_range then
                table.insert(ranged_players, unit)
            end
        end
    end

    return ranged_players
end


-- ========================================
-- EVENT REGISTRATION
-- ========================================
RegisterCreatureEvent(90300, 1, Boss.OnEnterCombat)    -- CREATURE_EVENT_ON_ENTER_COMBAT
RegisterCreatureEvent(90300, 2, Boss.OnLeaveCombat)    -- CREATURE_EVENT_ON_LEAVE_COMBAT
RegisterCreatureEvent(90300, 4, Boss.OnDied)           -- CREATURE_EVENT_ON_DIED
