-- Boss: Zhar'kaan the Stormheart
-- AUTO-GENERATED by world_builder.script_generator
-- Entry: 90400
-- COMPLETE AND DEPLOYABLE - NO MANUAL CHANGES REQUIRED

local Boss = {}

-- ========================================
-- SPELL CONSTANTS
-- ========================================
local SPELL_LIGHTNING_BOLT = 9532  -- Existing spell (reused)
local SPELL_ARC_LIGHTNING = 90030  -- Custom spell
local SPELL_SUMMON_STORM_WISPS = 90031  -- Custom spell
local SPELL_STORMWALL = 90032  -- Custom spell
local SPELL_EYE_OF_STORM = 90033  -- Custom spell
local SPELL_TEMPEST = 90034  -- Custom spell
local SPELL_CHAIN_LIGHTNING_ULTIMATE = 90035  -- Custom spell

-- ========================================
-- PHASE CONSTANTS
-- ========================================
local PHASE_GATHERING = 1
local PHASE_STORMWALL = 2
local PHASE_TEMPEST = 3

-- ========================================
-- NPC CONSTANTS
-- ========================================
local NPC_STORM_WISP = 90401  -- Storm Wisp

-- ========================================
-- ACHIEVEMENT TRACKING
-- ========================================
local achievement_eye_of_storm_hits = 0


-- ========================================
-- COMBAT EVENTS
-- ========================================
function Boss.OnEnterCombat(event, creature, target)
    -- Reset achievement tracking
    achievement_eye_of_storm_hits = 0


    -- Set initial phase
    creature:SetData("PHASE", 1)

    -- Phase 1 yell
    creature:SendUnitYell("You dare enter MY sanctum? The storm itself shall be your executioner!", 0)
    creature:PlayDirectSound(15030)

    -- Start Phase 1 ability timers
    creature:RegisterEvent(Boss.CastLightningBolt, 3000, 0)
    creature:RegisterEvent(Boss.CastArcLightning, 8000, 0)
    creature:RegisterEvent(Boss.SummonStormWisps, 10000, 0)

    -- Start phase check timer (every 1 second)
    creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
end

function Boss.OnLeaveCombat(event, creature)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Reset phase
    creature:SetData("PHASE", 0)

    -- Reset achievement tracking
    achievement_eye_of_storm_hits = 0


    -- Despawn any summoned adds
    local cleanup_1 = creature:GetCreaturesInRange(100, 90401)
    for _, add in pairs(cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

function Boss.OnDied(event, creature, killer)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Death yell
    creature:SendUnitYell("The storm... is... eternal... You have won... nothing...", 0)
    creature:PlayDirectSound(15033)

    -- Check achievements
    -- Eye of the Storm Dancer: Defeat Zhar'kaan without any player being hit by Eye of the Storm
    if achievement_eye_of_storm_hits == 0 then
        local players = creature:GetPlayersInRange(1000)
        for _, player in pairs(players) do
            if player:IsInCombat() then
                player:CompletedAchievement(90004)
            end
        end
    end


    -- Notify instance script
    local instance = creature:GetInstanceData()
    if instance then
        -- Update encounter state (Boss 3 = Zhar'kaan the Stormheart)
        local encounter_id = 3
        local state = instance:GetData("ENCOUNTER_STATE") or 0
        state = bit.bor(state, bit.lshift(1, encounter_id))
        instance:SetData("ENCOUNTER_STATE", state)

        -- Save instance data
        instance:SaveInstanceData()
    end

    -- Despawn remaining adds
    local death_cleanup_1 = creature:GetCreaturesInRange(100, 90401)
    for _, add in pairs(death_cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

-- ========================================
-- PHASE TRANSITIONS
-- ========================================
function Boss.CheckPhaseTransition(event, delay, repeats, creature)
    local hp_pct = creature:GetHealthPct()
    local current_phase = creature:GetData("PHASE")

    -- Phase 2 transition at 65% HP
    if hp_pct <= 65 and current_phase == 1 then
        creature:SetData("PHASE", 2)

        -- Phase transition yell
        creature:SendUnitYell("The walls close in! There is no escape from the eye of the storm!", 0)
        creature:PlayDirectSound(15031)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Start Phase 2 ability timers
        creature:RegisterEvent(Boss.CastStormwall, 5000, 0)
        creature:RegisterEvent(Boss.CastEyeOfStorm, 7000, 0)
        creature:RegisterEvent(Boss.SummonStormWispsP2, 12000, 0)
        creature:RegisterEvent(Boss.CastArcLightningP2, 10000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

    -- Phase 3 transition at 30% HP
    if hp_pct <= 30 and current_phase == 2 then
        creature:SetData("PHASE", 3)

        -- Phase transition yell
        creature:SendUnitYell("BEHOLD THE TEMPEST UNLEASHED! ALL SHALL BE CONSUMED!", 0)
        creature:PlayDirectSound(15032)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Start Phase 3 ability timers
        creature:RegisterEvent(Boss.CastTempest, 2000, 0)
        creature:RegisterEvent(Boss.CastChainLightningUltimate, 6000, 0)
        creature:RegisterEvent(Boss.SummonStormWispsP3, 5000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

end

-- ========================================
-- ABILITY FUNCTIONS
-- ========================================

-- ----------------------------------------
-- Phase 1 - Gathering Storm
-- ----------------------------------------

-- Lightning Bolt (Single target lightning at tank)
function Boss.CastLightningBolt(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target current victim (tank)
    local target = creature:GetVictim()

    if target then
        creature:CastSpell(target, 9532, false)
    end

    -- Reschedule
    local next_cast = math.random(4000, 6000)
    creature:RegisterEvent(Boss.CastLightningBolt, next_cast, 0)
end

-- Arc Lightning (Chain lightning hitting 4 targets)
function Boss.CastArcLightning(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90030, false)
    end

    -- Reschedule
    local next_cast = math.random(12000, 15000)
    creature:RegisterEvent(Boss.CastArcLightning, next_cast, 0)
end

-- Summon Storm Wisps (Summons 3 Storm Wisps every 25 seconds)
function Boss.SummonStormWisps(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Summon 3 adds at random positions around boss
    for i = 1, 3 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 15.0 * math.cos(angle)
        local spawn_y = y + 15.0 * math.sin(angle)

        local add = creature:SummonCreature(90401, spawn_x, spawn_y, z, o, 1, 0)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.SummonStormWisps, 25000, 0)
end

-- ----------------------------------------
-- Phase 2 - Stormwall
-- ----------------------------------------

-- Stormwall (Shrinks the arena by 20 percent, damages players outside)
function Boss.CastStormwall(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90032, false)
    end

    -- Reschedule
    creature:RegisterEvent(Boss.CastStormwall, 30000, 0)
end

-- Eye of the Storm (Targeted circle on player, must move out)
function Boss.CastEyeOfStorm(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Target random player for void zone placement
    local target = Boss.GetRandomPlayer(creature)
    if target then
        -- Cast visual spell at target location
        creature:CastSpell(target, 90033, false)
    end

    -- Reschedule
    local next_cast = math.random(12000, 18000)
    creature:RegisterEvent(Boss.CastEyeOfStorm, next_cast, 0)
end

-- Summon Storm Wisps (Wisps continue spawning)
function Boss.SummonStormWispsP2(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Summon 3 adds at random positions around boss
    for i = 1, 3 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 15.0 * math.cos(angle)
        local spawn_y = y + 15.0 * math.sin(angle)

        local add = creature:SummonCreature(90401, spawn_x, spawn_y, z, o, 1, 0)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.SummonStormWispsP2, 25000, 0)
end

-- Arc Lightning (Continues from Phase 1)
function Boss.CastArcLightningP2(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90030, false)
    end

    -- Reschedule
    local next_cast = math.random(10000, 14000)
    creature:RegisterEvent(Boss.CastArcLightningP2, next_cast, 0)
end

-- ----------------------------------------
-- Phase 3 - Tempest
-- ----------------------------------------

-- Tempest (Ramping AoE damage, increases every tick)
function Boss.CastTempest(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 3
    if current_phase ~= 3 then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90034, false)
    end

    -- Reschedule
    creature:RegisterEvent(Boss.CastTempest, 2000, 0)
end

-- Chain Lightning (Uninterruptible chain lightning, 6 targets)
function Boss.CastChainLightningUltimate(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 3
    if current_phase ~= 3 then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90035, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 12000)
    creature:RegisterEvent(Boss.CastChainLightningUltimate, next_cast, 0)
end

-- Summon Storm Wisps (Wisps spawn faster in final phase)
function Boss.SummonStormWispsP3(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 3
    if current_phase ~= 3 then
        return
    end

    -- Summon 3 adds at random positions around boss
    for i = 1, 3 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 15.0 * math.cos(angle)
        local spawn_y = y + 15.0 * math.sin(angle)

        local add = creature:SummonCreature(90401, spawn_x, spawn_y, z, o, 1, 0)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.SummonStormWispsP3, 15000, 0)
end

-- ========================================
-- HELPER FUNCTIONS
-- ========================================
function Boss.GetRandomPlayer(creature)
    local threat_list = creature:GetAITargets()
    local players = {}

    -- Filter for players only
    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            table.insert(players, unit)
        end
    end

    -- Return random player
    if #players > 0 then
        return players[math.random(1, #players)]
    end

    -- Fallback to current victim
    return creature:GetVictim()
end

function Boss.GetPlayersInMeleeRange(creature)
    local threat_list = creature:GetAITargets()
    local melee_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() and creature:GetDistance(unit) <= 5.0 then
            table.insert(melee_players, unit)
        end
    end

    return melee_players
end

function Boss.GetPlayersAtRange(creature, min_range, max_range)
    local threat_list = creature:GetAITargets()
    local ranged_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            local dist = creature:GetDistance(unit)
            if dist >= min_range and dist <= max_range then
                table.insert(ranged_players, unit)
            end
        end
    end

    return ranged_players
end


-- ========================================
-- EVENT REGISTRATION
-- ========================================
RegisterCreatureEvent(90400, 1, Boss.OnEnterCombat)    -- CREATURE_EVENT_ON_ENTER_COMBAT
RegisterCreatureEvent(90400, 2, Boss.OnLeaveCombat)    -- CREATURE_EVENT_ON_LEAVE_COMBAT
RegisterCreatureEvent(90400, 4, Boss.OnDied)           -- CREATURE_EVENT_ON_DIED
