-- Vault of Storms Instance Script
-- AUTO-GENERATED by world_builder.script_generator
-- Map ID: 801
-- COMPLETE AND DEPLOYABLE - NO MANUAL CHANGES REQUIRED

local INSTANCE = {}

-- ========================================
-- ENCOUNTER CONSTANTS
-- ========================================
INSTANCE.BOSS_SHADE = 0
INSTANCE.BOSS_OVERSEER = 1
INSTANCE.BOSS_GORGASH = 2
INSTANCE.BOSS_ZHARKAAN = 3
INSTANCE.MAX_ENCOUNTERS = 4

-- ========================================
-- DOOR ENTRIES
-- ========================================
INSTANCE.DOOR_NEXUS_TO_CORE = 195000
INSTANCE.DOOR_CORE_TO_FORGE = 195001
INSTANCE.DOOR_FORGE_TO_SANCTUM = 195002

-- ========================================
-- BOSS ENTRIES
-- ========================================
INSTANCE.NPC_SHADE = 90100
INSTANCE.NPC_OVERSEER = 90200
INSTANCE.NPC_GORGASH = 90300
INSTANCE.NPC_ZHARKAAN = 90400

-- ========================================
-- INSTANCE DATA KEYS
-- ========================================
local DATA_ENCOUNTER_STATE = "ENCOUNTER_STATE"
local DATA_DOOR_STATE = "DOOR_STATE"

-- ========================================
-- INSTANCE INITIALIZATION
-- ========================================
function INSTANCE.OnCreate(event, instance)
    -- Initialize encounter state (bitmask: 0 = not killed, 1 = killed)
    instance:SetData(DATA_ENCOUNTER_STATE, 0)

    -- Lock all doors initially
    INSTANCE.SetDoorState(instance, INSTANCE.DOOR_NEXUS_TO_CORE, 0)  -- closed
    INSTANCE.SetDoorState(instance, INSTANCE.DOOR_CORE_TO_FORGE, 0)  -- closed
    INSTANCE.SetDoorState(instance, INSTANCE.DOOR_FORGE_TO_SANCTUM, 0)  -- closed

    -- Initialize door state tracking
    instance:SetData(DATA_DOOR_STATE, 0)
end

-- ========================================
-- DOOR MANAGEMENT
-- ========================================
function INSTANCE.SetDoorState(instance, door_entry, state)
    local door = instance:GetGameObject(door_entry)
    if door then
        door:SetGoState(state)  -- 0 = closed, 1 = open
    end
end

function INSTANCE.UnlockDoor(instance, door_entry)
    INSTANCE.SetDoorState(instance, door_entry, 1)

    -- Update door state bitmask
    local door_state = instance:GetData(DATA_DOOR_STATE) or 0
    if door_entry == INSTANCE.DOOR_NEXUS_TO_CORE then
        door_state = bit.bor(door_state, 1)
    elseif door_entry == INSTANCE.DOOR_CORE_TO_FORGE then
        door_state = bit.bor(door_state, 2)
    elseif door_entry == INSTANCE.DOOR_FORGE_TO_SANCTUM then
        door_state = bit.bor(door_state, 4)
    end
    instance:SetData(DATA_DOOR_STATE, door_state)
end

-- ========================================
-- ENCOUNTER STATE MANAGEMENT
-- ========================================
function INSTANCE.SetBossState(instance, encounter_id, killed)
    local state = instance:GetData(DATA_ENCOUNTER_STATE) or 0

    if killed then
        -- Set encounter bit
        state = bit.bor(state, bit.lshift(1, encounter_id))
        instance:SetData(DATA_ENCOUNTER_STATE, state)

        -- Unlock corresponding door
        if encounter_id == INSTANCE.BOSS_SHADE then
            INSTANCE.UnlockDoor(instance, INSTANCE.DOOR_NEXUS_TO_CORE)
        elseif encounter_id == INSTANCE.BOSS_OVERSEER then
            INSTANCE.UnlockDoor(instance, INSTANCE.DOOR_CORE_TO_FORGE)
        elseif encounter_id == INSTANCE.BOSS_GORGASH then
            INSTANCE.UnlockDoor(instance, INSTANCE.DOOR_FORGE_TO_SANCTUM)
        end

        -- Save instance data
        instance:SaveInstanceData()
    end
end

function INSTANCE.IsBossKilled(instance, encounter_id)
    local state = instance:GetData(DATA_ENCOUNTER_STATE) or 0
    return bit.band(state, bit.lshift(1, encounter_id)) ~= 0
end

-- ========================================
-- INSTANCE DATA PERSISTENCE
-- ========================================
function INSTANCE.OnSave(event, instance)
    local state = instance:GetData(DATA_ENCOUNTER_STATE) or 0
    local door_state = instance:GetData(DATA_DOOR_STATE) or 0

    -- Save data (format: "encounterState doorState")
    return tostring(state) .. " " .. tostring(door_state)
end

function INSTANCE.OnLoad(event, instance, data)
    if not data or data == "" then
        return
    end

    -- Parse saved data
    local state, door_state = data:match("(%d+) (%d+)")
    state = tonumber(state) or 0
    door_state = tonumber(door_state) or 0

    -- Restore encounter state
    instance:SetData(DATA_ENCOUNTER_STATE, state)
    instance:SetData(DATA_DOOR_STATE, door_state)

    -- Restore door states based on killed bosses
    if INSTANCE.IsBossKilled(instance, INSTANCE.BOSS_SHADE) then
        INSTANCE.SetDoorState(instance, INSTANCE.DOOR_NEXUS_TO_CORE, 1)
    end
    if INSTANCE.IsBossKilled(instance, INSTANCE.BOSS_OVERSEER) then
        INSTANCE.SetDoorState(instance, INSTANCE.DOOR_CORE_TO_FORGE, 1)
    end
    if INSTANCE.IsBossKilled(instance, INSTANCE.BOSS_GORGASH) then
        INSTANCE.SetDoorState(instance, INSTANCE.DOOR_FORGE_TO_SANCTUM, 1)
    end
end

-- ========================================
-- CREATURE REGISTRATION
-- ========================================
function INSTANCE.OnCreatureCreate(event, instance, creature)
    local entry = creature:GetEntry()

    -- Register bosses for instance tracking
    if entry == INSTANCE.NPC_SHADE then
        instance:SetData("BOSS_" .. entry, creature:GetGUID())
    elseif entry == INSTANCE.NPC_OVERSEER then
        instance:SetData("BOSS_" .. entry, creature:GetGUID())
    elseif entry == INSTANCE.NPC_GORGASH then
        instance:SetData("BOSS_" .. entry, creature:GetGUID())
    elseif entry == INSTANCE.NPC_ZHARKAAN then
        instance:SetData("BOSS_" .. entry, creature:GetGUID())
    end
end

-- ========================================
-- EVENT REGISTRATION
-- ========================================
RegisterInstanceEvent(801, 1, INSTANCE.OnCreate)         -- INSTANCE_EVENT_ON_INITIALIZE
RegisterInstanceEvent(801, 3, INSTANCE.OnCreatureCreate) -- INSTANCE_EVENT_ON_CREATURE_CREATE
RegisterInstanceEvent(801, 5, INSTANCE.OnLoad)           -- INSTANCE_EVENT_ON_LOAD
RegisterInstanceEvent(801, 6, INSTANCE.OnSave)           -- INSTANCE_EVENT_ON_SAVE
