-- Spell Constants for Vault of Storms
-- AUTO-GENERATED by world_builder.script_generator
-- Maps readable spell names to spell IDs

-- ========================================
-- BOSS 1: SHADE OF ZHAR'KAAN
-- ========================================
SPELL_SHADOW_BOLT_VOLLEY = 27831              -- Existing: Shadow Bolt Volley (reused from Naxxramas)
SPELL_SUMMON_WISPS = 90001                    -- Custom: Summon Darkling Wisps
SPELL_SHADOW_POOL = 90002                     -- Custom: Shadow Pool visual
SPELL_SHADOW_POOL_DAMAGE = 90003              -- Custom: Shadow Pool damage aura
SPELL_LIGHTNING_LASH = 90004                  -- Custom: Lightning Lash (chain lightning)

-- ========================================
-- BOSS 2: OVERSEER CONSTRUCT V-7
-- ========================================
SPELL_SLAM = 90010                            -- Custom: Slam (tank)
SPELL_ARCANE_BOLT = 90011                     -- Custom: Arcane Bolt (random player)
SPELL_ACTIVATE_TURRET = 90012                 -- Custom: Activate Turret (script trigger)
SPELL_OVERCHARGED = 90013                     -- Custom: Overcharged (+10% damage stacking)
SPELL_ARCANE_PULSE = 90014                    -- Custom: Arcane Pulse (AoE)
SPELL_REACTIVATE_TURRETS = 90015              -- Custom: Reactivate All Turrets (script trigger)

-- ========================================
-- BOSS 3: GORGASH, STORMFATHER
-- ========================================
SPELL_THUNDEROUS_SLAM = 90020                 -- Custom: Thunderous Slam (cone)
SPELL_CALL_ZEALOTS = 90021                    -- Custom: Call Storm Zealots (summon)
SPELL_PRIMAL_ROAR = 90022                     -- Custom: Primal Roar (fear)
SPELL_STATIC_FIELD = 90023                    -- Custom: Static Field (periodic AoE)
SPELL_STATIC_FIELD_DOUBLE = 90024             -- Custom: Static Field Enhanced (double damage)
SPELL_LIGHTNING_CHARGE = 90025                -- Custom: Lightning Charge (dash)
SPELL_STORMHEART_FURY = 90026                 -- Custom: Stormheart Fury (+50% attack speed)

-- ========================================
-- BOSS 4: ZHAR'KAAN THE STORMHEART
-- ========================================
SPELL_LIGHTNING_BOLT = 9532                   -- Existing: Lightning Bolt (existing)
SPELL_ARC_LIGHTNING = 90030                   -- Custom: Arc Lightning (chain 4)
SPELL_SUMMON_STORM_WISPS = 90031              -- Custom: Summon Storm Wisps
SPELL_STORMWALL = 90032                       -- Custom: Stormwall (arena shrink)
SPELL_EYE_OF_STORM = 90033                    -- Custom: Eye of the Storm (targeted circle)
SPELL_TEMPEST = 90034                         -- Custom: Tempest (ramping AoE)
SPELL_CHAIN_LIGHTNING_ULTIMATE = 90035        -- Custom: Chain Lightning (uninterruptible, chain 6)

-- ========================================
-- NOTES
-- ========================================
-- Custom spell IDs (90000-90999) require spell_dbc entries
-- Existing spell IDs reuse WoW 3.3.5a spells for similar effects
-- For custom spells, create spell_template entries with appropriate effects
