-- Boss: Overseer Construct V-7
-- AUTO-GENERATED by world_builder.script_generator
-- Entry: 90200
-- COMPLETE AND DEPLOYABLE - NO MANUAL CHANGES REQUIRED

local Boss = {}

-- ========================================
-- SPELL CONSTANTS
-- ========================================
local SPELL_SLAM = 90010  -- Custom spell
local SPELL_ARCANE_BOLT = 90011  -- Custom spell
local SPELL_ACTIVATE_TURRET = 90012  -- Custom spell
local SPELL_ARCANE_PULSE = 90014  -- Custom spell
local SPELL_REACTIVATE_TURRETS = 90015  -- Custom spell

-- ========================================
-- PHASE CONSTANTS
-- ========================================
local PHASE_OPERATIONAL = 1
local PHASE_OVERCHARGED = 2

-- ========================================
-- NPC CONSTANTS
-- ========================================
local NPC_WALL_TURRET = 90201  -- Wall Turret

-- ========================================
-- ACHIEVEMENT TRACKING
-- ========================================
local achievement_turrets_destroyed = 0


-- ========================================
-- COMBAT EVENTS
-- ========================================
function Boss.OnEnterCombat(event, creature, target)
    -- Reset achievement tracking
    achievement_turrets_destroyed = 0


    -- Set initial phase
    creature:SetData("PHASE", 1)

    -- Phase 1 yell
    creature:SendUnitYell("INTRUDERS DETECTED. INITIATING DEFENSE PROTOCOL.", 0)
    creature:PlayDirectSound(15010)

    -- Start Phase 1 ability timers
    creature:RegisterEvent(Boss.CastSlam, 6000, 0)
    creature:RegisterEvent(Boss.CastArcaneBolt, 4000, 0)
    creature:RegisterEvent(Boss.ActivateTurret, 15000, 0)

    -- Start phase check timer (every 1 second)
    creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
end

function Boss.OnLeaveCombat(event, creature)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Reset phase
    creature:SetData("PHASE", 0)

    -- Reset achievement tracking
    achievement_turrets_destroyed = 0


    -- Despawn any summoned adds
    local cleanup_1 = creature:GetCreaturesInRange(100, 90201)
    for _, add in pairs(cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

function Boss.OnDied(event, creature, killer)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Death yell
    creature:SendUnitYell("SYSTEM... FAILURE...", 0)
    creature:PlayDirectSound(15012)

    -- Check achievements
    -- Short Circuit: Defeat Overseer Construct V-7 without destroying any turrets
    if achievement_turrets_destroyed == 0 then
        local players = creature:GetPlayersInRange(1000)
        for _, player in pairs(players) do
            if player:IsInCombat() then
                player:CompletedAchievement(90002)
            end
        end
    end


    -- Notify instance script
    local instance = creature:GetInstanceData()
    if instance then
        -- Update encounter state (Boss 1 = Overseer Construct V-7)
        local encounter_id = 1
        local state = instance:GetData("ENCOUNTER_STATE") or 0
        state = bit.bor(state, bit.lshift(1, encounter_id))
        instance:SetData("ENCOUNTER_STATE", state)

        -- Unlock door
        local door = instance:GetGameObject(195001)
        if door then
            door:SetGoState(1)  -- Open
        end

        -- Save instance data
        instance:SaveInstanceData()
    end

    -- Despawn remaining adds
    local death_cleanup_1 = creature:GetCreaturesInRange(100, 90201)
    for _, add in pairs(death_cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

-- ========================================
-- PHASE TRANSITIONS
-- ========================================
function Boss.CheckPhaseTransition(event, delay, repeats, creature)
    local hp_pct = creature:GetHealthPct()
    local current_phase = creature:GetData("PHASE")

    -- Phase 2 transition at 40% HP
    if hp_pct <= 40 and current_phase == 1 then
        creature:SetData("PHASE", 2)

        -- Phase transition yell
        creature:SendUnitYell("POWER CORE UNSTABLE. ENGAGING OVERDRIVE.", 0)
        creature:PlayDirectSound(15011)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Apply buff
        creature:CastSpell(creature, 90013, false)

        -- Start Phase 2 ability timers
        creature:RegisterEvent(Boss.CastSlamP2, 4000, 0)
        creature:RegisterEvent(Boss.CastArcanePulse, 5000, 0)
        creature:RegisterEvent(Boss.ReactivateTurrets, 8000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

end

-- ========================================
-- ABILITY FUNCTIONS
-- ========================================

-- ----------------------------------------
-- Phase 1 - Operational
-- ----------------------------------------

-- Slam (Heavy slam on current tank)
function Boss.CastSlam(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Target current victim (tank)
    local target = creature:GetVictim()

    if target then
        creature:CastSpell(target, 90010, false)
    end

    -- Reschedule
    local next_cast = math.random(10000, 14000)
    creature:RegisterEvent(Boss.CastSlam, next_cast, 0)
end

-- Arcane Bolt (Arcane bolt at random player)
function Boss.CastArcaneBolt(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90011, false)
    end

    -- Reschedule
    local next_cast = math.random(7000, 10000)
    creature:RegisterEvent(Boss.CastArcaneBolt, next_cast, 0)
end

-- Activate Turret (Activates 1 of 3 wall turrets to fire at players)
function Boss.ActivateTurret(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Activate 1 turret(s)
    local turrets = creature:GetCreaturesInRange(100, 90201)
    local activated = 0
    for _, turret in pairs(turrets) do
        if activated < 1 then
            turret:SetData("ACTIVE", 1)
            -- Turret will auto-deactivate after duration
            turret:RegisterEvent(function(ev, d, r, t)
                t:SetData("ACTIVE", 0)
                t:RemoveEvents()
            end, 20000, 1)
            activated = activated + 1
        end
    end

    -- Reschedule
    local next_cast = math.random(25000, 30000)
    creature:RegisterEvent(Boss.ActivateTurret, next_cast, 0)
end

-- ----------------------------------------
-- Phase 2 - Overcharged
-- ----------------------------------------

-- Slam (Continues from Phase 1, faster)
function Boss.CastSlamP2(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Target current victim (tank)
    local target = creature:GetVictim()

    if target then
        creature:CastSpell(target, 90010, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 10000)
    creature:RegisterEvent(Boss.CastSlamP2, next_cast, 0)
end

-- Arcane Pulse (AoE arcane pulse, unavoidable)
function Boss.CastArcanePulse(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 90014, false)
    end

    -- Reschedule
    local next_cast = math.random(12000, 15000)
    creature:RegisterEvent(Boss.CastArcanePulse, next_cast, 0)
end

-- Reactivate All Turrets (All turrets reactivate and fire continuously)
function Boss.ReactivateTurrets(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Activate 3 turret(s)
    local turrets = creature:GetCreaturesInRange(100, 90201)
    local activated = 0
    for _, turret in pairs(turrets) do
        if activated < 3 then
            turret:SetData("ACTIVE", 1)
            -- Turret will auto-deactivate after duration
            turret:RegisterEvent(function(ev, d, r, t)
                t:SetData("ACTIVE", 0)
                t:RemoveEvents()
            end, 15000, 1)
            activated = activated + 1
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.ReactivateTurrets, 30000, 0)
end

-- ========================================
-- HELPER FUNCTIONS
-- ========================================
function Boss.GetRandomPlayer(creature)
    local threat_list = creature:GetAITargets()
    local players = {}

    -- Filter for players only
    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            table.insert(players, unit)
        end
    end

    -- Return random player
    if #players > 0 then
        return players[math.random(1, #players)]
    end

    -- Fallback to current victim
    return creature:GetVictim()
end

function Boss.GetPlayersInMeleeRange(creature)
    local threat_list = creature:GetAITargets()
    local melee_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() and creature:GetDistance(unit) <= 5.0 then
            table.insert(melee_players, unit)
        end
    end

    return melee_players
end

function Boss.GetPlayersAtRange(creature, min_range, max_range)
    local threat_list = creature:GetAITargets()
    local ranged_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            local dist = creature:GetDistance(unit)
            if dist >= min_range and dist <= max_range then
                table.insert(ranged_players, unit)
            end
        end
    end

    return ranged_players
end


-- ========================================
-- EVENT REGISTRATION
-- ========================================
RegisterCreatureEvent(90200, 1, Boss.OnEnterCombat)    -- CREATURE_EVENT_ON_ENTER_COMBAT
RegisterCreatureEvent(90200, 2, Boss.OnLeaveCombat)    -- CREATURE_EVENT_ON_LEAVE_COMBAT
RegisterCreatureEvent(90200, 4, Boss.OnDied)           -- CREATURE_EVENT_ON_DIED
