-- Boss: Shade of Zhar'kaan
-- AUTO-GENERATED by world_builder.script_generator
-- Entry: 90100
-- COMPLETE AND DEPLOYABLE - NO MANUAL CHANGES REQUIRED

local Boss = {}

-- ========================================
-- SPELL CONSTANTS
-- ========================================
local SPELL_SHADOW_BOLT_VOLLEY = 27831  -- Existing spell (reused)
local SPELL_SUMMON_WISPS = 90001  -- Custom spell
local SPELL_SHADOW_POOL = 90002  -- Custom spell
local SPELL_LIGHTNING_LASH = 90004  -- Custom spell
local SPELL_SHADOW_POOL_DAMAGE = 90003  -- Custom spell (damage aura)

-- ========================================
-- PHASE CONSTANTS
-- ========================================
local PHASE_SHADOW = 1
local PHASE_STORM = 2

-- ========================================
-- NPC CONSTANTS
-- ========================================
local NPC_DARKLING_WISP = 90101  -- Darkling Wisp
local NPC_SHADOWY_STALKER = 90102  -- Shadowy Stalker

-- ========================================
-- ACHIEVEMENT TRACKING
-- ========================================
local achievement_shadow_pool_hits = 0


-- ========================================
-- COMBAT EVENTS
-- ========================================
function Boss.OnEnterCombat(event, creature, target)
    -- Reset achievement tracking
    achievement_shadow_pool_hits = 0


    -- Set initial phase
    creature:SetData("PHASE", 1)

    -- Phase 1 yell
    creature:SendUnitYell("The shadows consume you!", 0)
    creature:PlayDirectSound(15000)

    -- Start Phase 1 ability timers
    creature:RegisterEvent(Boss.CastShadowBoltVolley, 5000, 0)
    creature:RegisterEvent(Boss.SummonWisps, 10000, 0)
    creature:RegisterEvent(Boss.CastShadowPool, 8000, 0)

    -- Start phase check timer (every 1 second)
    creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
end

function Boss.OnLeaveCombat(event, creature)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Reset phase
    creature:SetData("PHASE", 0)

    -- Reset achievement tracking
    achievement_shadow_pool_hits = 0


    -- Despawn any summoned adds
    local cleanup_1 = creature:GetCreaturesInRange(100, 90101)
    for _, add in pairs(cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
    local cleanup_2 = creature:GetCreaturesInRange(100, 90102)
    for _, add in pairs(cleanup_2) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

function Boss.OnDied(event, creature, killer)
    -- Clean up all timers
    creature:RemoveEvents()

    -- Death yell
    creature:SendUnitYell("The darkness... recedes...", 0)
    creature:PlayDirectSound(15002)

    -- Check achievements
    -- Shadow Dance: Defeat Shade of Zhar'kaan without any player being hit by Shadow Pool
    if achievement_shadow_pool_hits == 0 then
        local players = creature:GetPlayersInRange(1000)
        for _, player in pairs(players) do
            if player:IsInCombat() then
                player:CompletedAchievement(90001)
            end
        end
    end


    -- Notify instance script
    local instance = creature:GetInstanceData()
    if instance then
        -- Update encounter state (Boss 0 = Shade of Zhar'kaan)
        local encounter_id = 0
        local state = instance:GetData("ENCOUNTER_STATE") or 0
        state = bit.bor(state, bit.lshift(1, encounter_id))
        instance:SetData("ENCOUNTER_STATE", state)

        -- Unlock door
        local door = instance:GetGameObject(195000)
        if door then
            door:SetGoState(1)  -- Open
        end

        -- Save instance data
        instance:SaveInstanceData()
    end

    -- Despawn remaining adds
    local death_cleanup_1 = creature:GetCreaturesInRange(100, 90101)
    for _, add in pairs(death_cleanup_1) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
    local death_cleanup_2 = creature:GetCreaturesInRange(100, 90102)
    for _, add in pairs(death_cleanup_2) do
        if add:IsAlive() then
            add:DespawnOrUnsummon(0)
        end
    end
end

-- ========================================
-- PHASE TRANSITIONS
-- ========================================
function Boss.CheckPhaseTransition(event, delay, repeats, creature)
    local hp_pct = creature:GetHealthPct()
    local current_phase = creature:GetData("PHASE")

    -- Phase 2 transition at 50% HP
    if hp_pct <= 50 and current_phase == 1 then
        creature:SetData("PHASE", 2)

        -- Phase transition yell
        creature:SendUnitYell("The storm awakens! You cannot contain what was never meant to be caged!", 0)
        creature:PlayDirectSound(15001)

        -- Remove all previous phase timers
        creature:RemoveEvents()

        -- Transform adds: 90101 -> 90102
        local old_adds = creature:GetCreaturesInRange(100, 90101)
        for _, add in pairs(old_adds) do
            if add:IsAlive() then
                local ax, ay, az, ao = add:GetLocation()
                add:DespawnOrUnsummon(0)
                creature:SummonCreature(90102, ax, ay, az, ao, 1, 0)
            end
        end

        -- Start Phase 2 ability timers
        creature:RegisterEvent(Boss.CastLightningLash, 3000, 0)
        creature:RegisterEvent(Boss.CastShadowBoltVolleyP2, 8000, 0)

        -- Re-register phase check timer
        creature:RegisterEvent(Boss.CheckPhaseTransition, 1000, 0)
        return
    end

end

-- ========================================
-- ABILITY FUNCTIONS
-- ========================================

-- ----------------------------------------
-- Phase 1 - Shadow Phase
-- ----------------------------------------

-- Shadow Bolt Volley (AoE shadow damage, interruptible)
function Boss.CastShadowBoltVolley(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 27831, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 12000)
    creature:RegisterEvent(Boss.CastShadowBoltVolley, next_cast, 0)
end

-- Summon Darkling Wisps (Summons 2 Darkling Wisps to attack players)
function Boss.SummonWisps(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Summon 2 adds at random positions around boss
    for i = 1, 2 do
        local angle = math.random() * 2 * math.pi
        local x, y, z, o = creature:GetLocation()
        local spawn_x = x + 10.0 * math.cos(angle)
        local spawn_y = y + 10.0 * math.sin(angle)

        local add = creature:SummonCreature(90101, spawn_x, spawn_y, z, o, 1, 60000)
        if add then
            -- Attack a random player
            local target = Boss.GetRandomPlayer(creature)
            if target then
                add:Attack(target)
            end
        end
    end

    -- Reschedule
    creature:RegisterEvent(Boss.SummonWisps, 20000, 0)
end

-- Shadow Pool (Void zone at random player location)
function Boss.CastShadowPool(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 1
    if current_phase ~= 1 then
        return
    end

    -- Target random player for void zone placement
    local target = Boss.GetRandomPlayer(creature)
    if target then
        -- Cast visual spell at target location
        creature:CastSpell(target, 90002, false)
    end

    -- Reschedule
    local next_cast = math.random(15000, 20000)
    creature:RegisterEvent(Boss.CastShadowPool, next_cast, 0)
end

-- ----------------------------------------
-- Phase 2 - Storm Phase
-- ----------------------------------------

-- Lightning Lash (Chain lightning, hits 3 targets)
function Boss.CastLightningLash(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Target random player
    local target = Boss.GetRandomPlayer(creature)

    if target then
        creature:CastSpell(target, 90004, false)
    end

    -- Reschedule
    local next_cast = math.random(6000, 10000)
    creature:RegisterEvent(Boss.CastLightningLash, next_cast, 0)
end

-- Shadow Bolt Volley (Continues from Phase 1)
function Boss.CastShadowBoltVolleyP2(event, delay, repeats, creature)
    local current_phase = creature:GetData("PHASE")

    -- Only in Phase 2
    if current_phase ~= 2 then
        return
    end

    -- Don't cast if already casting
    if creature:IsCasting() then
        return
    end

    -- Target self (AoE effect)
    local target = creature

    if target then
        creature:CastSpell(target, 27831, false)
    end

    -- Reschedule
    local next_cast = math.random(8000, 12000)
    creature:RegisterEvent(Boss.CastShadowBoltVolleyP2, next_cast, 0)
end

-- ========================================
-- HELPER FUNCTIONS
-- ========================================
function Boss.GetRandomPlayer(creature)
    local threat_list = creature:GetAITargets()
    local players = {}

    -- Filter for players only
    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            table.insert(players, unit)
        end
    end

    -- Return random player
    if #players > 0 then
        return players[math.random(1, #players)]
    end

    -- Fallback to current victim
    return creature:GetVictim()
end

function Boss.GetPlayersInMeleeRange(creature)
    local threat_list = creature:GetAITargets()
    local melee_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() and creature:GetDistance(unit) <= 5.0 then
            table.insert(melee_players, unit)
        end
    end

    return melee_players
end

function Boss.GetPlayersAtRange(creature, min_range, max_range)
    local threat_list = creature:GetAITargets()
    local ranged_players = {}

    for _, unit in pairs(threat_list) do
        if unit:IsPlayer() then
            local dist = creature:GetDistance(unit)
            if dist >= min_range and dist <= max_range then
                table.insert(ranged_players, unit)
            end
        end
    end

    return ranged_players
end


-- ========================================
-- EVENT REGISTRATION
-- ========================================
RegisterCreatureEvent(90100, 1, Boss.OnEnterCombat)    -- CREATURE_EVENT_ON_ENTER_COMBAT
RegisterCreatureEvent(90100, 2, Boss.OnLeaveCombat)    -- CREATURE_EVENT_ON_LEAVE_COMBAT
RegisterCreatureEvent(90100, 4, Boss.OnDied)           -- CREATURE_EVENT_ON_DIED
