"""
WoW 3.3.5a AddOn scaffold generator.

Generates complete AddOn boilerplate (TOC, Lua, XML) for WoW WotLK 3.3.5a.
The generated AddOns follow Blizzard's standard AddOn structure and use
the 3.3.5a-compatible API.
"""

import os
import logging

log = logging.getLogger(__name__)


def generate_addon(
    name,
    output_dir,
    title=None,
    description=None,
    frames=None,
    events=None,
    slash_commands=None,
    saved_variables=None,
    author=None,
    version='1.0',
):
    """
    Generate a complete WoW 3.3.5 AddOn (TOC + Lua + optional XML).

    Args:
        name: AddOn folder and file name (e.g. 'MyAddon').
        output_dir: Parent directory for the AddOn folder.
        title: Display title in AddOn list (default: name).
        description: AddOn description (shown in AddOn list notes).
        frames: Optional list of frame definitions, each a dict with:
            - 'name': Frame global name (e.g. 'MyAddonMainFrame')
            - 'parent': Parent frame (default 'UIParent')
            - 'width': Frame width (default 300)
            - 'height': Frame height (default 200)
            - 'point': Anchor point (default 'CENTER')
            - 'movable': Whether frame is movable (default False)
            - 'backdrop': Whether to add backdrop (default True)
        events: Optional list of event name strings to register
                (e.g. ['PLAYER_LOGIN', 'ADDON_LOADED']).
        slash_commands: Optional list of slash command dicts:
            - 'command': Slash command (e.g. '/myaddon')
            - 'handler': Lua code string for the handler body
        saved_variables: Optional list of saved variable names.
        author: Author name for TOC file.
        version: Version string for TOC file (default '1.0').

    Returns:
        dict: {
            'addon_dir': str,   # Path to addon folder
            'toc_path': str,    # Path to .toc file
            'lua_path': str,    # Path to .lua file
            'xml_path': str or None,  # Path to .xml file (if frames defined)
        }
    """
    if title is None:
        title = name
    if events is None:
        events = []
    if frames is None:
        frames = []
    if slash_commands is None:
        slash_commands = []
    if saved_variables is None:
        saved_variables = []

    addon_dir = os.path.join(output_dir, name)
    os.makedirs(addon_dir, exist_ok=True)

    toc_path = os.path.join(addon_dir, '{}.toc'.format(name))
    lua_path = os.path.join(addon_dir, '{}.lua'.format(name))
    xml_path = None

    # --- Generate TOC ---
    toc_lines = [
        '## Interface: 30300',
        '## Title: {}'.format(title),
    ]
    if description:
        toc_lines.append('## Notes: {}'.format(description))
    if author:
        toc_lines.append('## Author: {}'.format(author))
    toc_lines.append('## Version: {}'.format(version))

    if saved_variables:
        toc_lines.append('## SavedVariables: {}'.format(', '.join(saved_variables)))

    # File list
    if frames:
        xml_path = os.path.join(addon_dir, '{}.xml'.format(name))
        toc_lines.append('{}.xml'.format(name))
    toc_lines.append('{}.lua'.format(name))
    toc_lines.append('')  # trailing newline

    with open(toc_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(toc_lines))

    # --- Generate Lua ---
    lua_lines = [
        '-- {}'.format(title),
        '-- Generated by pywowlib world_builder',
        '',
    ]

    # Saved variables initialization
    for sv in saved_variables:
        lua_lines.append('{} = {} or {{}}'.format(sv, sv))
    if saved_variables:
        lua_lines.append('')

    # Event handler frame
    if events or slash_commands:
        lua_lines.append('local eventFrame = CreateFrame("Frame")')
        for event in events:
            lua_lines.append('eventFrame:RegisterEvent("{}")'.format(event))
        lua_lines.append('')

        lua_lines.append('eventFrame:SetScript("OnEvent", function(self, event, ...)')
        for event in events:
            lua_lines.append('    if event == "{}" then'.format(event))
            lua_lines.append('        -- Handle {}'.format(event))
            lua_lines.append('    end')
        lua_lines.append('end)')
        lua_lines.append('')

    # Slash commands
    for i, cmd in enumerate(slash_commands):
        cmd_name = cmd.get('command', '/{}'.format(name.lower()))
        handler = cmd.get('handler', 'print("{} command executed")'.format(name))

        # Register slash command
        slug = name.upper()
        lua_lines.append('SLASH_{}1 = "{}"'.format(slug, cmd_name))
        lua_lines.append('SlashCmdList["{}"] = function(msg)'.format(slug))
        lua_lines.append('    {}'.format(handler))
        lua_lines.append('end')
        lua_lines.append('')

    lua_lines.append('')  # trailing newline

    with open(lua_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lua_lines))

    # --- Generate XML (only if frames defined) ---
    if frames:
        xml_lines = [
            '<Ui xmlns="http://www.blizzard.com/wow/ui/"',
            '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
            '    xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\\FrameXML\\UI.xsd">',
            '',
        ]

        for frame_def in frames:
            fname = frame_def.get('name', '{}MainFrame'.format(name))
            parent = frame_def.get('parent', 'UIParent')
            width = frame_def.get('width', 300)
            height = frame_def.get('height', 200)
            point = frame_def.get('point', 'CENTER')
            movable = frame_def.get('movable', False)
            backdrop = frame_def.get('backdrop', True)

            xml_lines.append('    <Frame name="{}" parent="{}" movable="{}" enableMouse="true">'.format(
                fname, parent, 'true' if movable else 'false'))
            xml_lines.append('        <Size x="{}" y="{}"/>'.format(width, height))
            xml_lines.append('        <Anchors>')
            xml_lines.append('            <Anchor point="{}"/>'.format(point))
            xml_lines.append('        </Anchors>')

            if backdrop:
                xml_lines.append('        <Backdrop bgFile="Interface\\DialogFrame\\UI-DialogBox-Background"')
                xml_lines.append('                  edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border" tile="true">')
                xml_lines.append('            <BackgroundInsets left="11" right="12" top="12" bottom="11"/>')
                xml_lines.append('            <TileSize val="32"/>')
                xml_lines.append('            <EdgeSize val="32"/>')
                xml_lines.append('        </Backdrop>')

            if movable:
                xml_lines.append('        <Scripts>')
                xml_lines.append('            <OnMouseDown>')
                xml_lines.append('                self:StartMoving()')
                xml_lines.append('            </OnMouseDown>')
                xml_lines.append('            <OnMouseUp>')
                xml_lines.append('                self:StopMovingOrSizing()')
                xml_lines.append('            </OnMouseUp>')
                xml_lines.append('        </Scripts>')

            xml_lines.append('    </Frame>')
            xml_lines.append('')

        xml_lines.append('</Ui>')
        xml_lines.append('')

        with open(xml_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(xml_lines))

    log.info("Generated AddOn '%s' in %s", name, addon_dir)

    return {
        'addon_dir': addon_dir,
        'toc_path': toc_path,
        'lua_path': lua_path,
        'xml_path': xml_path,
    }
