"""
Spell ID registry for WoW WotLK 3.3.5a boss encounters.

Manages spell ID assignments for boss encounters and instance scripts.
Maps readable spell names to numeric spell IDs, supporting both custom
spell IDs (90000+ range) and reuse of existing WoW 3.3.5a spells.

Custom spell IDs in the 90000-90999 range require corresponding
spell_dbc entries on the server side. Existing spell IDs reuse
WoW 3.3.5a spells that have suitable visual/mechanical effects.
"""

import json
import os
import re
import logging

log = logging.getLogger(__name__)


class SpellRegistry:
    """
    Manages spell ID assignments for boss encounters.

    Maps readable spell names to spell IDs. Supports both custom spell
    IDs (auto-assigned from a configurable base) and reusing existing
    WoW spell IDs for their visual/mechanical effects.
    """

    def __init__(self, base_spell_id=90000):
        """
        Initialize spell registry.

        Args:
            base_spell_id: Starting ID for custom spells (default: 90000).
                           Each call to register_spell without an existing_spell_id
                           will consume the next available ID from this counter.
        """
        self.base_spell_id = base_spell_id
        self.next_spell_id = base_spell_id
        self.spell_map = {}            # name -> spell_id
        self.spell_definitions = []    # list of spell metadata dicts
        self._boss_groups = {}         # spell_name -> boss_label (for export grouping)

    def register_spell(self, spell_name, existing_spell_id=None,
                       custom_spell_id=None, description='',
                       spell_data=None, boss_label=None):
        """
        Register a spell. If *existing_spell_id* is provided, reuse that
        spell. If *custom_spell_id* is provided, use that explicit custom ID.
        Otherwise assign a new custom spell ID from the auto-increment counter.

        Args:
            spell_name: Identifier (e.g. 'SPELL_SHADOW_BOLT_VOLLEY').
            existing_spell_id: Optional existing WoW spell ID to reuse.
            custom_spell_id: Optional explicit custom spell ID to use.
            description: Human-readable description of the spell.
            spell_data: Optional dict with additional spell properties.
            boss_label: Optional boss section label for grouped exports.

        Returns:
            int: The assigned or reused spell ID.
        """
        if spell_name in self.spell_map:
            return self.spell_map[spell_name]

        if existing_spell_id:
            spell_id = existing_spell_id
            spell_type = 'existing'
        elif custom_spell_id:
            spell_id = custom_spell_id
            spell_type = 'custom'
            # Advance auto counter past this ID if needed
            if spell_id >= self.next_spell_id:
                self.next_spell_id = spell_id + 1
        else:
            spell_id = self.next_spell_id
            self.next_spell_id += 1
            spell_type = 'custom'

        self.spell_map[spell_name] = spell_id
        self.spell_definitions.append({
            'spell_id': spell_id,
            'spell_name': spell_name,
            'description': description,
            'type': spell_type,
            'data': spell_data or {},
        })

        if boss_label:
            self._boss_groups[spell_name] = boss_label

        return spell_id

    def resolve_spell_id(self, spell_name):
        """
        Get the spell ID for a given spell name.

        Args:
            spell_name: The registered spell identifier.

        Returns:
            int: Spell ID, or 0 if not found.
        """
        return self.spell_map.get(spell_name, 0)

    def get_all_spells(self):
        """
        Return a copy of all spell definitions.

        Returns:
            list[dict]: List of spell definition dicts.
        """
        return list(self.spell_definitions)

    def export_lua_constants(self, filepath):
        """
        Export spell constants as a Lua file grouped by boss section.

        Args:
            filepath: Path to write spell_constants.lua.
        """
        parent = os.path.dirname(filepath)
        if parent:
            os.makedirs(parent, exist_ok=True)

        with open(filepath, 'w') as f:
            f.write("-- Spell Constants for Vault of Storms\n")
            f.write("-- AUTO-GENERATED by world_builder.script_generator\n")
            f.write("-- Maps readable spell names to spell IDs\n")

            current_group = None
            for spell_def in self.spell_definitions:
                group = self._boss_groups.get(
                    spell_def['spell_name'],
                    self._infer_boss_name(spell_def['spell_name']),
                )

                if group != current_group:
                    current_group = group
                    f.write("\n-- ========================================\n")
                    f.write("-- {}\n".format(current_group))
                    f.write("-- ========================================\n")

                spell_id = spell_def['spell_id']
                spell_name = spell_def['spell_name']
                description = spell_def['description']
                spell_type = spell_def['type']

                if description:
                    comment = "-- {}: {}".format(spell_type.capitalize(), description)
                else:
                    comment = "-- {}".format(spell_type.capitalize())

                # Pad spell name = id for alignment
                assignment = "{} = {}".format(spell_name, spell_id)
                f.write("{:<45} {}\n".format(assignment, comment))

            f.write("\n-- ========================================\n")
            f.write("-- NOTES\n")
            f.write("-- ========================================\n")
            f.write("-- Custom spell IDs (90000-90999) require spell_dbc entries\n")
            f.write("-- Existing spell IDs reuse WoW 3.3.5a spells for similar effects\n")
            f.write("-- For custom spells, create spell_template entries with appropriate effects\n")

    def export_json_config(self, filepath):
        """
        Export spell configuration as JSON for documentation.

        Args:
            filepath: Path to write spell_config.json.
        """
        parent = os.path.dirname(filepath)
        if parent:
            os.makedirs(parent, exist_ok=True)

        with open(filepath, 'w') as f:
            json.dump({
                'spell_map': self.spell_map,
                'spell_definitions': self.spell_definitions,
            }, f, indent=2)

    # ------------------------------------------------------------------
    # Import methods
    # ------------------------------------------------------------------

    def import_from_json(self, filepath):
        """
        Import spells from a JSON file matching ``export_json_config()`` format.

        Reads the JSON file and registers each spell definition found in
        the ``spell_definitions`` array via ``register_spell()``.

        Args:
            filepath: Path to the JSON spell configuration file.

        Returns:
            int: Number of spells imported.
        """
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)

        count = 0
        for spell_def in data.get('spell_definitions', []):
            spell_name = spell_def.get('spell_name', '')
            if not spell_name:
                continue

            spell_id = spell_def.get('spell_id', 0)
            spell_type = spell_def.get('type', 'custom')
            description = spell_def.get('description', '')
            spell_data = spell_def.get('data', None)

            if spell_type == 'existing':
                self.register_spell(
                    spell_name,
                    existing_spell_id=spell_id,
                    description=description,
                    spell_data=spell_data,
                )
            else:
                self.register_spell(
                    spell_name,
                    custom_spell_id=spell_id,
                    description=description,
                    spell_data=spell_data,
                )
            count += 1

        log.info("Imported %d spells from JSON: %s", count, filepath)
        return count

    def import_from_lua(self, filepath):
        """
        Import spells from a Lua constants file.

        Parses lines matching ``NAME = 12345`` patterns. Uses
        ``-- BOSS: label`` or ``-- boss_label`` comment lines to infer
        boss grouping for each subsequent spell constant.

        Args:
            filepath: Path to the Lua spell constants file.

        Returns:
            int: Number of spells imported.
        """
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        assignment_re = re.compile(r'^(\w+)\s*=\s*(\d+)')
        boss_comment_re = re.compile(r'^--\s*(?:BOSS:\s*)?(.+)', re.IGNORECASE)

        current_boss = None
        count = 0

        for line in lines:
            stripped = line.strip()

            # Check for boss label comment
            boss_match = boss_comment_re.match(stripped)
            if boss_match and '=' not in stripped:
                label = boss_match.group(1).strip()
                # Skip generic comment lines (notes, separators, etc.)
                if label and not label.startswith('=') and len(label) > 2:
                    current_boss = label

            # Check for spell assignment
            assign_match = assignment_re.match(stripped)
            if assign_match:
                spell_name = assign_match.group(1)
                spell_id = int(assign_match.group(2))

                # Extract inline description from trailing comment
                description = ''
                comment_idx = stripped.find('--')
                if comment_idx > 0:
                    description = stripped[comment_idx + 2:].strip()

                self.register_spell(
                    spell_name,
                    custom_spell_id=spell_id,
                    description=description,
                    boss_label=current_boss,
                )
                count += 1

        log.info("Imported %d spells from Lua: %s", count, filepath)
        return count

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _infer_boss_name(self, spell_name):
        """Infer boss name from spell name for grouping in exports."""
        name = spell_name.upper()

        if any(k in name for k in ('SHADOW', 'WISP', 'LIGHTNING_LASH')):
            return "BOSS 1: SHADE OF ZHAR'KAAN"
        if any(k in name for k in ('SLAM', 'ARCANE', 'TURRET', 'OVERCHARGED')):
            return "BOSS 2: OVERSEER CONSTRUCT V-7"
        if any(k in name for k in ('THUNDEROUS', 'ZEALOT', 'PRIMAL',
                                    'STATIC', 'STORMHEART_FURY')):
            return "BOSS 3: GORGASH, STORMFATHER"
        if any(k in name for k in ('BOLT', 'ARC', 'STORM_WISP', 'STORMWALL',
                                    'EYE_OF_STORM', 'TEMPEST', 'CHAIN')):
            return "BOSS 4: ZHAR'KAAN THE STORMHEART"

        return "MISC"
