"""
Elwynn Forest Modification Test Script

Uses the full procedural pipeline to generate a modified ADT for Elwynn
Forest tile (3, 4) and packs it into patch-4.MPQ for the WoW 3.3.5a client.

Pipeline:
    plan_zone() -> sculpt_for_adt_composer() -> create_adt() -> MPQ pack

All terrain is seeded procedural generation via SimplexNoise in the
terrain_sculptor. The seed is configurable for reproducible results.

Usage:
    python tools/test_elwynn_modification.py [--seed N] [--archetype NAME]
    python tools/test_elwynn_modification.py --seed 42 --archetype forested_highlands
    python tools/test_elwynn_modification.py --archetype volcanic_island --no-copy
    python tools/test_elwynn_modification.py --list-archetypes

After running:
    1. The script copies patch-4.MPQ to the WoW Data directory
    2. Restart the WoW client
    3. Log in and visit Goldshire / Northshire in Elwynn Forest
    4. You should see procedurally generated terrain matching the archetype

To revert:
    Delete G:\\WoW AzerothCore\\Data\\patch-4.MPQ
"""

import argparse
import os
import shutil
import struct
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from world_builder.zone_planner import (plan_zone, preview_heightmap,
                                         list_archetypes, list_landmark_types)
from world_builder.terrain_sculptor import sculpt_for_adt_composer
from world_builder.adt_composer import create_adt, add_doodad_to_adt
from world_builder.mpq_packer import MPQPacker


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Real WoW tile size: 533.333 yards (64x64 grid, total map ~34133 yards)
# adt_composer.py TILE_SIZE is now correct (533.333). The fix_adt_mcnk_positions
# function below is kept for backward compatibility but is no longer needed.
_WOW_TILE_SIZE = 533.33333333
_WOW_CHUNK_SIZE = _WOW_TILE_SIZE / 16.0  # ~33.333 yards per chunk
_WOW_MAP_SIZE_MAX = 17066.66657

# Elwynn Forest tile coordinates
# Goldshire is at world coords approx (-9459, 62) -> tile (31, 49).
ELWYNN_TILE_X = 31
ELWYNN_TILE_Y = 49
MAP_NAME = "Azeroth"

# Elwynn Forest area IDs (from DBC)
ELWYNN_AREA_ID = 12


def fix_adt_mcnk_positions(adt_bytes, tile_x, tile_y):
    """Patch MCNK chunk positions in an ADT to use real WoW coordinates.

    DEPRECATED: adt_composer.py TILE_SIZE is now correct (533.333).
    This function is no longer needed and should not be called on ADTs
    generated by the current adt_composer. Kept for backward compatibility.

    MCNK header layout (128 bytes, starting after 8-byte chunk header):
        offset  0: flags (4B)
        offset  4: index_x/chunk_col (4B)
        offset  8: index_y/chunk_row (4B)
        ...
        offset 104: position x,y,z (3 floats, 12B)

    Args:
        adt_bytes: Raw ADT file bytes from create_adt().
        tile_x: Real WoW tile X coordinate (0-63).
        tile_y: Real WoW tile Y coordinate (0-63).

    Returns:
        bytes: Patched ADT bytes with correct MCNK positions.
    """
    data = bytearray(adt_bytes)
    mcnk_magic = b'KNCM'  # Reversed — WoW stores chunk magic in little-endian
    patched = 0

    i = 0
    while i < len(data) - 4:
        if data[i:i + 4] == mcnk_magic:
            # Found MCNK chunk at offset i
            # Chunk header: 4 bytes magic + 4 bytes size = 8 bytes
            # MCNK header starts at i+8
            hdr_start = i + 8

            # Read chunk_col (index_x) and chunk_row (index_y)
            chunk_col = struct.unpack_from('<I', data, hdr_start + 4)[0]
            chunk_row = struct.unpack_from('<I', data, hdr_start + 8)[0]

            # Calculate correct WoW position
            pos_x = _WOW_MAP_SIZE_MAX - (tile_y * _WOW_TILE_SIZE) - (chunk_row * _WOW_CHUNK_SIZE)
            pos_y = _WOW_MAP_SIZE_MAX - (tile_x * _WOW_TILE_SIZE) - (chunk_col * _WOW_CHUNK_SIZE)
            pos_z = 0.0

            # Patch position at MCNK header offset 104
            struct.pack_into('<fff', data, hdr_start + 104, pos_x, pos_y, pos_z)
            patched += 1

            # Skip past this MCNK (read its size to jump ahead)
            chunk_size = struct.unpack_from('<I', data, i + 4)[0]
            i += 8 + chunk_size
        else:
            i += 1

    if patched != 256:
        print("  WARNING: Patched {} MCNK chunks (expected 256)".format(patched))
    else:
        print("  Patched {} MCNK positions to tile ({}, {})".format(patched, tile_x, tile_y))

    return bytes(data)


# Default landmarks for the forested_highlands archetype -- gives a
# recognisable landscape with varied terrain features.
DEFAULT_LANDMARKS = [
    {'type': 'peak', 'position': 'center', 'elevation': 80,
     'name': 'Goldshire Hill'},
    {'type': 'forest', 'position': 'northeast', 'density': 'dense',
     'name': 'Northshire Woods'},
    {'type': 'lake', 'position': (0.3, 0.7), 'radius': 0.08,
     'name': 'Crystal Lake'},
    {'type': 'village', 'position': (0.5, 0.6), 'radius': 0.06,
     'name': 'Goldshire'},
    {'type': 'ridge', 'position': 'northwest', 'radius': 0.10,
     'name': 'Stone Cairn Ridge'},
]

# Archetype-specific landmark presets
ARCHETYPE_LANDMARKS = {
    'volcanic_island': [
        {'type': 'volcano', 'position': 'center',
         'rim_height': 120, 'caldera_depth': 40, 'has_lava': True,
         'name': 'Ashfall Caldera'},
        {'type': 'beach', 'position': 'south', 'radius': 0.12,
         'name': 'Ember Beach'},
        {'type': 'village', 'position': (0.5, 0.8), 'radius': 0.06,
         'name': 'Ember Haven'},
    ],
    'frozen_peaks': [
        {'type': 'peak', 'position': 'center', 'elevation': 130,
         'name': 'Frost Summit'},
        {'type': 'peak', 'position': 'northwest', 'elevation': 100,
         'name': 'Ice Spire'},
        {'type': 'cave', 'position': (0.6, 0.4), 'radius': 0.04,
         'name': 'Frozen Hollow'},
    ],
    'desert_canyon': [
        {'type': 'cliff', 'position': 'center', 'radius': 0.15,
         'name': 'Sand Canyon'},
        {'type': 'ruins', 'position': (0.3, 0.4), 'radius': 0.06,
         'name': 'Lost Temple'},
        {'type': 'pond', 'position': (0.7, 0.7), 'radius': 0.04,
         'name': 'Desert Oasis'},
    ],
    'tropical_jungle': [
        {'type': 'forest', 'position': 'center', 'density': 'thick',
         'name': 'Deep Jungle'},
        {'type': 'lake', 'position': (0.3, 0.3), 'radius': 0.07,
         'name': 'Jungle Pool'},
        {'type': 'ruins', 'position': (0.7, 0.4), 'radius': 0.06,
         'name': 'Troll Ruins'},
        {'type': 'beach', 'position': 'south', 'radius': 0.10,
         'name': 'Palm Shore'},
    ],
    'dark_forest': [
        {'type': 'forest', 'position': 'center', 'density': 'thick',
         'name': 'Darkwood Thicket'},
        {'type': 'cave', 'position': (0.7, 0.3), 'radius': 0.04,
         'name': 'Shadow Cave'},
        {'type': 'ruins', 'position': (0.3, 0.6), 'radius': 0.05,
         'name': 'Abandoned Manor'},
        {'type': 'pond', 'position': (0.5, 0.7), 'radius': 0.04,
         'name': 'Dark Pond'},
    ],
    'mushroom_marsh': [
        {'type': 'lake', 'position': 'center', 'radius': 0.10,
         'name': 'Spore Lake'},
        {'type': 'forest', 'position': 'east', 'density': 'dense',
         'name': 'Mushroom Grove'},
        {'type': 'village', 'position': (0.3, 0.7), 'radius': 0.05,
         'name': 'Sporeggar Camp'},
    ],
    'rolling_meadow': [
        {'type': 'village', 'position': 'center', 'radius': 0.07,
         'name': 'Meadow Town'},
        {'type': 'lake', 'position': (0.7, 0.3), 'radius': 0.06,
         'name': 'Sunspring Lake'},
        {'type': 'forest', 'position': 'northeast', 'density': 'moderate',
         'name': 'Hilltop Grove'},
        {'type': 'peak', 'position': 'northwest', 'elevation': 60,
         'name': 'Windy Knoll'},
    ],
    'nordic_fjord': [
        {'type': 'cliff', 'position': 'center', 'radius': 0.12,
         'name': 'Fjord Cliff'},
        {'type': 'forest', 'position': 'east', 'density': 'dense',
         'name': 'Pine Forest'},
        {'type': 'village', 'position': (0.5, 0.8), 'radius': 0.06,
         'name': 'Fjord Village'},
        {'type': 'beach', 'position': 'south', 'radius': 0.10,
         'name': 'Rocky Shore'},
    ],
}


def build_elwynn_patch(output_dir, wow_data_dir=None, archetype='forested_highlands',
                       seed=42, landmarks=None):
    """Build a patch-4.MPQ with procedurally generated terrain.

    Args:
        output_dir: Where to write intermediate and output files.
        wow_data_dir: Path to WoW Data directory. If provided, copies
                      the MPQ there automatically.
        archetype: Zone archetype name (e.g. 'forested_highlands').
        seed: Random seed for reproducible procedural generation.
        landmarks: List of landmark dicts. If None, uses archetype defaults.

    Returns:
        str: Path to the generated patch-4.MPQ file.
    """
    os.makedirs(output_dir, exist_ok=True)

    print("=" * 60)
    print("Elwynn Forest Procedural Modification Test")
    print("=" * 60)
    print("  Archetype:  {}".format(archetype))
    print("  Seed:       {}".format(seed))
    print("  Tile:       ({}, {})".format(ELWYNN_TILE_X, ELWYNN_TILE_Y))

    # Step 1: Plan zone using the procedural planner
    if landmarks is None:
        landmarks = ARCHETYPE_LANDMARKS.get(archetype, DEFAULT_LANDMARKS)

    print("\n[1/5] Planning zone with {} landmarks...".format(len(landmarks)))
    for lm in landmarks:
        print("  - {}: {} at {}".format(
            lm.get('name', '(unnamed)'), lm['type'], lm['position']))

    zone_def = plan_zone(
        name="ElwynnTest",
        archetype=archetype,
        landmarks=landmarks,
        grid_size=(1, 1),
        base_coords=(ELWYNN_TILE_X, ELWYNN_TILE_Y),
        seed=seed,
        area_id_start=ELWYNN_AREA_ID,
    )

    print("  Subzones generated: {}".format(len(zone_def.get('subzones', []))))
    for sz in zone_def.get('subzones', []):
        print("    - {} (area_id={}, terrain={})".format(
            sz.get('name', '?'), sz.get('area_id', 0),
            sz.get('terrain_type', '?')))

    # Step 2: Preview heightmap stats
    print("\n[2/5] Previewing heightmap statistics...")
    stats = preview_heightmap(zone_def)
    g = stats.get('global', {})
    print("  Grid size: {}".format(zone_def.get('grid_size')))
    print("  Sea level: {}".format(zone_def.get('sea_level', 0)))
    print("  Elevation range: {:.1f} - {:.1f} yards".format(
        g.get('min_elevation', 0), g.get('max_elevation', 0)))
    print("  Mean elevation: {:.1f} yards".format(g.get('mean_elevation', 0)))

    # Step 3: Sculpt terrain procedurally
    print("\n[3/5] Sculpting terrain (procedural generation)...")
    tile_data = sculpt_for_adt_composer(zone_def)

    tile_key = (ELWYNN_TILE_X, ELWYNN_TILE_Y)
    if tile_key not in tile_data:
        print("  ERROR: Tile {} not found in sculpted output!".format(tile_key))
        print("  Available tiles: {}".format(list(tile_data.keys())))
        return None

    td = tile_data[tile_key]
    print("  Textures: {}".format(td.get('texture_paths', [])))
    print("  Doodads:  {} placements".format(len(td.get('doodads', []))))
    print("  WMOs:     {} placements".format(len(td.get('wmos', []))))
    print("  Water:    {} regions".format(len(td.get('water', []))))

    # Step 4: Create ADT binary
    print("\n[4/5] Creating ADT binary...")
    adt_bytes = create_adt(
        tile_x=ELWYNN_TILE_X,
        tile_y=ELWYNN_TILE_Y,
        heightmap=td['heightmap'],
        texture_paths=td['texture_paths'],
        splat_map=td.get('splat_map'),
        area_id=td.get('area_id', ELWYNN_AREA_ID),
    )

    # MCNK positions are now correct (TILE_SIZE fixed to 533.333).
    # fix_adt_mcnk_positions() is no longer needed.

    # Add doodads (M2 model placements)
    for doodad in td.get('doodads', []):
        try:
            adt_bytes = add_doodad_to_adt(
                adt_bytes,
                m2_path=doodad.get('model_path', doodad.get('m2_path', '')),
                position=doodad.get('position', (0, 0, 0)),
                rotation=doodad.get('rotation', (0, 0, 0)),
                scale=doodad.get('scale', 1024),
            )
        except Exception as e:
            pass  # Skip doodads that fail silently

    print("  ADT size: {:,} bytes".format(len(adt_bytes)))

    # Step 5: Pack into MPQ
    print("\n[5/5] Packing into patch-4.MPQ...")
    packer = MPQPacker(output_dir, patch_name="patch-4.MPQ")

    adt_mpq_path = "World\\Maps\\{}\\{}_{:d}_{:d}.adt".format(
        MAP_NAME, MAP_NAME, ELWYNN_TILE_X, ELWYNN_TILE_Y)
    packer.add_file(adt_mpq_path, adt_bytes)

    print("  MPQ internal path: {}".format(adt_mpq_path))

    mpq_path = packer.build_mpq()
    print("  Output: {}".format(mpq_path))

    # Copy to WoW Data directory
    if wow_data_dir:
        dest = os.path.join(wow_data_dir, "patch-4.MPQ")
        print("\n[+] Copying to WoW Data directory...")
        print("    Source: {}".format(mpq_path))
        print("    Dest:   {}".format(dest))

        if os.path.isfile(mpq_path):
            shutil.copy2(mpq_path, dest)
            print("    Done!")
        else:
            alt_path = os.path.join(output_dir, "patch-4.MPQ")
            if os.path.isfile(alt_path):
                shutil.copy2(alt_path, dest)
                print("    Found at alternate path and copied!")
            else:
                print("    WARNING: MPQ file not found. Check: {}".format(output_dir))

    # Summary
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print("  Pipeline:   plan_zone -> sculpt_for_adt_composer -> create_adt")
    print("  Archetype:  {}".format(archetype))
    print("  Seed:       {}".format(seed))
    print("  Map:        {} (Azeroth)".format(MAP_NAME))
    print("  Tile:       ({}, {})".format(ELWYNN_TILE_X, ELWYNN_TILE_Y))
    print("  Subzones:   {}".format(len(zone_def.get('subzones', []))))
    print("  Textures:   {}".format(td.get('texture_paths', [])))
    print("  Doodads:    {} placements".format(len(td.get('doodads', []))))
    print("  ADT size:   {:,} bytes".format(len(adt_bytes)))

    if wow_data_dir:
        print("\n  TESTING INSTRUCTIONS:")
        print("  1. The patch has been copied to your WoW Data directory")
        print("  2. Restart the WoW client (ADT changes require restart)")
        print("  3. Log in and go to Goldshire in Elwynn Forest")
        print("  4. You should see '{}' terrain with procedural features".format(archetype))
        print("  5. To revert: delete G:\\WoW AzerothCore\\Data\\patch-4.MPQ")
        print("  6. Try different seeds: --seed 123  (different terrain, same archetype)")
        print("  7. Try different biomes: --archetype volcanic_island")
    else:
        print("\n  To test: copy patch-4.MPQ to your WoW Data directory")
        print("  Then restart the WoW client and visit Elwynn Forest")

    return mpq_path


def main():
    parser = argparse.ArgumentParser(
        description="Generate a procedurally modified Elwynn Forest tile"
    )
    parser.add_argument(
        "--output-dir",
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                             "output", "elwynn_test"),
        help="Output directory for generated files",
    )
    parser.add_argument(
        "--wow-data",
        default="G:\\WoW AzerothCore\\Data",
        help="Path to WoW Data directory (for auto-copy)",
    )
    parser.add_argument(
        "--no-copy",
        action="store_true",
        help="Don't copy the MPQ to the WoW Data directory",
    )
    parser.add_argument(
        "--archetype",
        default="forested_highlands",
        help="Zone archetype (use --list-archetypes to see options)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for procedural generation (default: 42)",
    )
    parser.add_argument(
        "--list-archetypes",
        action="store_true",
        help="List available archetypes and exit",
    )

    args = parser.parse_args()

    if args.list_archetypes:
        archetypes = list_archetypes()
        print("Available archetypes:")
        for key, desc in sorted(archetypes.items()):
            has_preset = " [has landmark preset]" if key in ARCHETYPE_LANDMARKS else ""
            print("  {:24s} {}{}".format(key, desc, has_preset))
        print("\nLandmark types: {}".format(', '.join(list_landmark_types())))
        return

    wow_data = None if args.no_copy else args.wow_data

    if wow_data and not os.path.isdir(wow_data):
        print("WARNING: WoW Data directory not found: {}".format(wow_data))
        print("         MPQ will be generated but not copied.")
        wow_data = None

    build_elwynn_patch(
        output_dir=args.output_dir,
        wow_data_dir=wow_data,
        archetype=args.archetype,
        seed=args.seed,
    )


if __name__ == "__main__":
    main()
